# Generated by Django 3.0.2 on 2020-02-11 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('line_item_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('product_sku', models.CharField(max_length=25)),
                ('properties', models.BooleanField()),
                ('variant_title', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=20)),
                ('order_number', models.CharField(max_length=20)),
                ('created_at', models.DateField()),
                ('assigned_to', models.CharField(max_length=25)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Assigned'), (2, 'Cutting'), (3, 'Ojales'), (4, 'Ready')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_sku', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('nombre_producto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seamstress',
            fields=[
                ('seamstress_id', models.AutoField(primary_key=True, serialize=False)),
                ('workshop', models.CharField(max_length=50)),
                ('seamstress_name', models.CharField(max_length=50)),
                ('seamstress_lastname', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('line_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_scheduler.LineItem')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.TextField()),
                ('order_number', models.CharField(max_length=20)),
                ('publication_date', models.DateTimeField()),
                ('line_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_scheduler.LineItem')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
