# Generated by Django 3.0.2 on 2020-02-19 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seamstress',
            name='seamstress_lastname',
        ),
        migrations.RemoveField(
            model_name='seamstress',
            name='seamstress_name',
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production_scheduler.Seamstress'),
        ),
    ]
