# Generated by Django 3.0.2 on 2020-03-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_scheduler', '0002_auto_20200219_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
