# Generated by Django 3.0.2 on 2020-03-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_scheduler', '0003_product_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Nueva'), (1, 'Asignada'), (2, 'Cortando'), (3, 'Armando'), (4, 'Terminada'), (5, 'Entregada')], default=0),
        ),
    ]
