# Generated by Django 3.0.2 on 2020-03-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_scheduler', '0004_auto_20200302_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nombre_producto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
