# Generated by Django 3.0.2 on 2020-03-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_scheduler', '0005_auto_20200302_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='special_instructions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
