# Generated by Django 3.0.2 on 2020-03-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_scheduler', '0006_lineitem_special_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='seamstress',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
