# Generated by Django 3.0.2 on 2020-04-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_scheduler', '0010_auto_20200401_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
