# Generated by Django 3.0.2 on 2020-04-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_scheduler', '0011_auto_20200407_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='order_number',
        ),
    ]
