# Generated by Django 3.0.2 on 2020-04-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_scheduler', '0012_remove_message_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seamstress',
            name='workshop',
        ),
    ]
