# Generated by Django 3.0.2 on 2020-04-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_scheduler', '0013_remove_seamstress_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='fecha_assignacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
