# Generated by Django 3.0.2 on 2020-04-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_scheduler', '0016_auto_20200422_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_event',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
