# Generated by Django 3.0.2 on 2020-04-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_scheduler', '0017_log_is_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='line_item_id',
        ),
        migrations.RemoveField(
            model_name='log',
            name='username',
        ),
        migrations.DeleteModel(
            name='InboxReadControl',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
